# Generated by Django 2.2 on 2020-02-22 16:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='城市名称')),
                ('desc', models.CharField(max_length=200, verbose_name='城市描述')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '城市',
                'verbose_name_plural': '城市',
            },
        ),
        migrations.CreateModel(
            name='CourseOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='机构名称')),
                ('desc', models.CharField(max_length=200, verbose_name='机构描述')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('favor', models.IntegerField(default=0, verbose_name='收藏数')),
                ('click', models.IntegerField(default=0, verbose_name='点击数')),
                ('address', models.CharField(max_length=150, verbose_name='机构地址')),
                ('image', models.ImageField(upload_to='orgs/%Y/%m', verbose_name='机构封面')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orgs', to='organizations.City')),
            ],
            options={
                'verbose_name': '机构',
                'verbose_name_plural': '机构',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favor', models.IntegerField(default=0, verbose_name='收藏数')),
                ('click', models.IntegerField(default=0, verbose_name='点击数')),
                ('name', models.CharField(max_length=50, verbose_name='讲师姓名')),
                ('work_years', models.IntegerField(default=0, verbose_name='工作年限')),
                ('work_company', models.CharField(max_length=50, verbose_name='工作公司')),
                ('work_position', models.CharField(max_length=50, verbose_name='工作职位')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('points', models.CharField(max_length=50, verbose_name='教学特点')),
                ('courseorg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='organizations.CourseOrg')),
            ],
            options={
                'verbose_name': '讲师',
                'verbose_name_plural': '讲师',
            },
        ),
    ]
