# Generated by Django 2.2 on 2020-02-25 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='kind',
            field=models.CharField(choices=[('per', '个人'), ('school', '高校'), ('pxjg', '培训机构')], default='pxjg', max_length=10, verbose_name='机构类别'),
        ),
    ]
